trojan://6582de70-607a-11ed-83b8-1239d0255272@sg1-trojan.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#HE
trojan://a44239f0-607a-11ed-a445-1239d0255272@sgovh-trojan.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#OVH
trojan://f2c50bb0-6406-11ed-be0d-1239d0255272@sg1-trojan.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#SG+HE
trojan://d1240d90-6406-11ed-8ee4-1239d0255272@sgovh-trojan.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#SG+OVH
trojan://0a53f810-6407-11ed-bf0c-1239d0255272@idtj-ikd.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#ID+IKD
