trojan://42ea3250-341d-11ed-bbeb-1239d0255272@sgovh-trojan.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#OVH
trojan://84ca0680-341d-11ed-9287-1239d0255272@trojan2.udpgw.com:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#LINODE
trojan://c4aa5de0-341d-11ed-9fbd-1239d0255272@idtj-herza.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#HERZA
