trojan://eed7bb40-4cef-11ed-9dfc-1239d0255272@sgovh-trojan.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#SG+OVH
trojan://6c6d8180-4cef-11ed-a168-1239d0255272@trojan2.udpgw.com:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#SG+LINODE
trojan://a934f870-4cef-11ed-997f-1239d0255272@idtj-ikd.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#ID+IKD
trojan://be827d20-4cef-11ed-9e81-1239d0255272@idtj-herza.bonds.id:443?security=tls&headerType=none&type=tcp&sni=kh.google.com#ID+HERZA
